development:
  adapter: postgresql
  encoding: utf8
  database: fror_dev
  username: user
  password: 
  host: localhost
test:
  adapter: postgresql
  encoding: utf8
  database: fror_dev
  username: user
  password: 
  host: localhost
